name: things
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.9.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  get_it: ^7.6.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
